apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: simple-deployment-pr-testing
  namespace: argocd
spec:
  generators:
  - pullRequest:
      github:
        owner: lloydsmithjr03
        repo: gitops-environment-promotion
        labels:
        - preview
      requeueAfterSeconds: 5
  template:
    metadata:
      name: 'simple-deployment-{{branch}}-{{number}}'
    spec:
      source:
        repoURL: 'https://github.com/lloydsmithjr03/gitops-environment-promotion'
        targetRevision: '{{head_sha}}'
        path: base
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      destination:
        server: https://kubernetes.default.svc
        namespace: 'simple-deployment-{{branch}}-{{number}}'