---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: simple-deployment
spec:
  template:
    spec:
      containers:
      - name: webserver-simple
        env:
        - name: ENV
          value: "qa"
        - name: GPU_ENABLED
          value: "1"
      