---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: simple-deployment
spec:
  template:
    spec:
      containers:
      - name: webserver-simple
        env:
        - name: ENV_TYPE
          value: "non-prod"
        - name: PAYPAL_URL
          value: "staging2.paypal.com"
        - name: DB_USER
          value: "non-prod-user"
        - name: DB_PASSWORD
          value: "non-prod-password"    