project: simple-env-kustomize
source:
  repoURL: 'https://github.com/lloydsmithjr03/gitops-environment-promotion'
  path: envs/prod-us
  targetRevision: HEAD
destination:
  server: 'https://kubernetes.default.svc'
  namespace: prod-us
syncPolicy:
  automated: {}
  syncOptions:
    - CreateNamespace=true
