apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging
namePrefix: staging-us-

resources:
- ../../base

components:
  - ../../variants/non-prod
  - ../../variants/eu

patchesStrategicMerge:
- deployment.yml
- version.yml
- replicas.yml
- settings.yml
- service.yml
- rollout.yml