---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: simple-deployment
  annotations:
    codefresh.io/app: simple-go-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trivial-go-web-app
  template:
    metadata:
      labels:
        app: trivial-go-web-app
    spec:
      containers:
      - name: webserver-simple
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
