on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true && contains( github.event.pull_request.labels.*.name, 'preview')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Copy files
        run: |
          cp base/version.yml envs/qa/version.yml
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.1.1
        with:
          commit-message: 'promote: base to qa'
          title: 'promote: base to qa'
          branch: "base-to-qa-${{github.event.pull_request.id}}"
          body: |
            Promotes base version to QA
          labels: qa