on:
  pull_request:
    types:
      - closed
  label:
    types:
      - qa
jobs:
  if_merged:
    if: github.event.pull_reqeuest.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Create staging PR
        uses: technote-space/create-pr-action@v2
         with:
           EXECUTE_COMMANDS: |
             cp envs/qa/version.yml envs/staging-us/version.yml
             cp envs/qa/version.yml envs/staging-eu/version.yml
           COMMIT_MESSAGE: 'chore: promote to staging'
           COMMIT_NAME: 'GitHub Actions'
           COMMIT_EMAIL: 'smithl@nuarxinc.com'
           PR_BRANCH_NAME: 'chore-promote-staging-${PR_ID}'
           PR_TITLE: 'chore: promote version to staging'
      
