on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true && contains( github.event.pull_request.labels.*.name, 'qa')
    runs-on: ubuntu-latest
    steps:
      - name: Create staging PR
        uses: technote-space/create-pr-action@v2
        with:
          EXECUTE_COMMANDS: |
            cp envs/qa/version.yml envs/staging-us/version.yml
            cp envs/qa/version.yml envs/staging-eu/version.yml
          COMMIT_MESSAGE: 'chore: promote to staging'
          COMMIT_NAME: 'GitHub Actions'
          COMMIT_EMAIL: 'smithl@nuarxinc.com'
          PR_BRANCH_NAME: 'chore-promote-production-${github.event.pull_request.id}'
          PR_TITLE: 'chore: promote version to staging'
          INCLUDE_LABELS: staging
      
